version: '3.1'
services:
  adminer:
    platform: linux/amd64
    image: hub.roky.work/library/adminer:5.1.0
    restart: always
    ports:
      - 7070:8080

  redis:
    platform: linux/amd64
    image: hub.roky.work/library/redis:6.0.6
    restart: always
    ports:
      - "6379:6379"

  db:
    platform: linux/amd64
    image: hub.roky.work/library/mysql:5.7.39
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "3306:3306"
    volumes:
      - ./.data:/var/lib/mysql
