# github.com/flipped-aurora/gin-vue-admin/server Global Configuration

# jwt configuration
jwt:
    signing-key: qmPlus
    expires-time: 7d
    buffer-time: 1d
    issuer: qmPlus
# zap logger configuration
zap:
    level: info
    format: console
    prefix: "[github.com/flipped-aurora/gin-vue-admin/server]"
    director: log
    show-line: true
    encode-level: LowercaseColorLevelEncoder
    stacktrace-key: stacktrace
    log-in-console: true
    retention-day: -1

# redis configuration
redis:
    #是否使用redis集群模式
    useCluster: false
    #使用集群模式addr和db默认无效
    addr: 177.7.0.14:6379
    password: ""
    db: 0
    clusterAddrs:
        - "177.7.0.14:7000"
        - "177.7.0.15:7001"
        - "177.7.0.13:7002"

# redis-list configuration
redis-list:
    - name: cache           # 数据库的名称,注意: name 需要在 redis-list 中唯一
      useCluster: false     # 是否使用redis集群模式
      addr: 177.7.0.14:6379  # 使用集群模式addr和db默认无效
      password: ""
      db: 0
      clusterAddrs:
          - "177.7.0.14:7000"
          - "177.7.0.15:7001"
          - "177.7.0.13:7002"

# mongo configuration
mongo:
    coll: ''
    options: ''
    database: ''
    username: ''
    password: ''
    auth-source: ''
    min-pool-size: 0
    max-pool-size: 100
    socket-timeout-ms: 0
    connect-timeout-ms: 0
    is-zap: false
    hosts:
        - host: ''
          port: ''

# email configuration
email:
    to: xxx@qq.com
    port: 465
    from: xxx@163.com
    host: smtp.163.com
    is-ssl: true
    secret: xxx
    nickname: test

# system configuration
system:
    env: local # 修改为public可以关闭路由日志输出
    addr: 8888
    db-type: mysql
    oss-type: local # 控制oss选择走本地还是 七牛等其他仓 自行增加其他oss仓可以在 server/utils/upload/upload.go 中 NewOss函数配置
    use-redis: false # 使用redis
    use-mongo: false     # 使用mongo
    use-multipoint: false
    # IP限制次数 一个小时15000次
    iplimit-count: 15000
    #  IP限制一个小时
    iplimit-time: 3600
    #  路由全局前缀
    router-prefix: ""
    #  严格角色模式 打开后权限将会存在上下级关系
    use-strict-auth: false

# captcha configuration
captcha:
    key-long: 6
    img-width: 240
    img-height: 80
    open-captcha: 0 # 0代表一直开启，大于0代表限制次数
    open-captcha-timeout: 3600 # open-captcha大于0时才生效

# mysql connect configuration
# 未初始化之前请勿手动修改数据库信息！！！如果一定要手动初始化请看（https://gin-vue-admin.com/docs/first_master）
mysql:
    path: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    max-idle-conns: 10
    max-open-conns: 100
    log-mode: ""
    log-zap: false

# pgsql connect configuration
# 未初始化之前请勿手动修改数据库信息！！！如果一定要手动初始化请看（https://gin-vue-admin.com/docs/first_master）
pgsql:
    path: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    max-idle-conns: 10
    max-open-conns: 100
    log-mode: ""
    log-zap: false
oracle:
    path: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    max-idle-conns: 10
    max-open-conns: 100
    log-mode: ""
    log-zap: false
mssql:
    path: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    max-idle-conns: 10
    max-open-conns: 100
    log-mode: ""
    log-zap: false
sqlite:
    path: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    max-idle-conns: 10
    max-open-conns: 100
    log-mode: ""
    log-zap: false
db-list:
    - disable: true # 是否禁用
      type: "" # 数据库的类型,目前支持mysql、pgsql、mssql、oracle
      alias-name: "" # 数据库的名称,注意: alias-name 需要在db-list中唯一
      path: ""
      port: ""
      config: ""
      db-name: ""
      username: ""
      password: ""
      max-idle-conns: 10
      max-open-conns: 100
      log-mode: ""
      log-zap: false

# local configuration
local:
    path: uploads/file
    store-path: uploads/file

# autocode configuration
autocode:
    web: web/src
    root: "" # root 自动适配项目根目录, 请不要手动配置,他会在项目加载的时候识别出根路径
    server: server
    module: 'github.com/flipped-aurora/gin-vue-admin/server'
    ai-path: ""  # AI服务路径

# qiniu configuration (请自行七牛申请对应的 公钥 私钥 bucket 和 域名地址)
qiniu:
    zone: ZoneHuaDong
    bucket: ""
    img-path: ""
    use-https: false
    access-key: ""
    secret-key: ""
    use-cdn-domains: false

# minio oss configuration
minio:
    endpoint: yourEndpoint
    access-key-id: yourAccessKeyId
    access-key-secret: yourAccessKeySecret
    bucket-name: yourBucketName
    use-ssl: false
    base-path: ""
    bucket-url: "http://host:9000/yourBucketName"

# aliyun oss configuration
aliyun-oss:
    endpoint: yourEndpoint
    access-key-id: yourAccessKeyId
    access-key-secret: yourAccessKeySecret
    bucket-name: yourBucketName
    bucket-url: yourBucketUrl
    base-path: yourBasePath

# tencent cos configuration
tencent-cos:
    bucket: xxxxx-10005608
    region: ap-shanghai
    secret-id: your-secret-id
    secret-key: your-secret-key
    base-url: https://gin.vue.admin
    path-prefix: github.com/flipped-aurora/gin-vue-admin/server

# aws s3 configuration (minio compatible)
aws-s3:
    bucket: xxxxx-10005608
    region: ap-shanghai
    endpoint: ""
    s3-force-path-style: false
    disable-ssl: false
    secret-id: your-secret-id
    secret-key: your-secret-key
    base-url: https://gin.vue.admin
    path-prefix: github.com/flipped-aurora/gin-vue-admin/server

# cloudflare r2 configuration
cloudflare-r2:
    bucket: xxxx0bucket
    base-url: https://gin.vue.admin.com
    path: uploads
    account-id: xxx_account_id
    access-key-id: xxx_key_id
    secret-access-key: xxx_secret_key

# huawei obs configuration
hua-wei-obs:
    path: you-path
    bucket: you-bucket
    endpoint: you-endpoint
    access-key: you-access-key
    secret-key: you-secret-key

# excel configuration
excel:
    dir: ./resource/excel/

# disk usage configuration
disk-list:
    - mount-point: "/"

# 跨域配置
# 需要配合 server/initialize/router.go -> `Router.Use(middleware.CorsByRules())` 使用
cors:
    mode: strict-whitelist # 放行模式: allow-all, 放行全部; whitelist, 白名单模式, 来自白名单内域名的请求添加 cors 头; strict-whitelist 严格白名单模式, 白名单外的请求一律拒绝
    whitelist:
        - allow-origin: example1.com
          allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
          allow-methods: POST, GET
          expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type

          allow-credentials: true # 布尔值
        - allow-origin: example2.com
          allow-headers: content-type
          allow-methods: GET, POST
          expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
          allow-credentials: true # 布尔值
mcp:
    name: GVA_MCP
    version: v1.0.0
    sse_path: /sse
    message_path: /message
    url_prefix: ''
    addr: 8889
    separate: false

casdoor:
    endpoint: "https://auth.rowenatech.com"
    client-id: "62c109b49d93a5985f06"
    client-secret: "ab88cf1d8ca82e7f24eebe96496fab3bd53783b2"
    certificate: |
        -----BEGIN CERTIFICATE-----
        MIIE3TCCAsWgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCgxEDAOBgNVBAoTB3Ry
        aXBsZWMxFDASBgNVBAMMC2NlcnRfZjYybDY5MB4XDTI1MDMyNjA1NTYyMloXDTQ1
        MDMyNjA1NTYyMlowKDEQMA4GA1UEChMHdHJpcGxlYzEUMBIGA1UEAwwLY2VydF9m
        NjJsNjkwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCf4/wCJh1lDZnd
        kRM+BQqbPnSBsUmyG/0xcVtwonhLrrIUlwpmQtTVOD5o7yvwjURQoLfB7PKw287u
        E1+Xol109dJN3bjQWBYtRXo7/7Fug+fmhlrwTF7duT6OD60UyGu9ZolRDWPwqde8
        eYZ5Y6dWuveh/bHZZawxdcQvBfrmUF9RI9jSgeGfgqCyeKSz9YiFPM/whx2ikJ69
        MebYY1pu0x/B4ztJW0L+pgRCcwZxCVqsVNYptaixb52Ust8f/dzyhylxHceZmPLc
        0i+sD07XWcv7TA/oDRhrcgzbsuLrBkgs0O1uGD9dl04Y3cbM0JeYBKD9W8H1Bw5z
        SvgzWmuIATXbcSKnoxUGbxbg/9nxvJuJ9S8wNTvSoUNML03/GFwByJd7kzCZFzHJ
        IyPwkkDR+kdJ1EBKV4T38d7Xfbb+XwJyDM1cbH5tTA9pxlrN8vHdqwjgZGEv20vh
        7Dv9VBXXr6+zk5ONB+zGI0KP498kZFcdlyV9+aafoJXvBVfZ3B0Ag6cJ071WWYJZ
        ktGgYCquGm93AslUrP4VFE90aG/V0klhiNPdAt48eT4F4smDsJOcZtXsyXS45N4x
        5eZq2QTph2ytaE7At7AOk3I3L5auZza4oPsfWeLUuvvnQuilLp9+9xRJLSmhjegS
        JKJ3/K7b3U0ZZSQEKFuQ53y/5/xkDwIDAQABoxAwDjAMBgNVHRMBAf8EAjAAMA0G
        CSqGSIb3DQEBCwUAA4ICAQAyEvyKMF85d6beBCRcH4Tlootu1ASMa92xQWx91+0N
        dU3fPMrnUGD5G9coAf10VEQ8WPO9Ji80JiqxTGKWBUzihchXqLT37Xao4eR43zAr
        BYS4/gPNxRtbO8E4vy37/I/SdG1YyOXYCGyguWoKoFLkQzvU4dxlVe7EJz2QoWc9
        RDliuz2rKvuRIAPx0Ug6uMyeK2c8WdpEiob6qOO+BZZHA8H/o/6kgEBcxFFP38fU
        cpo5hZWMDUp2XRB/ELKvga5OkwsY2mCBPIcqokxT7Hm80KtvLuDoPZjOYsrFShlV
        t4PQQpzwmuNi1UdsQx9aJYjoJ5KvX7K6iAw/NBnJkj/3btHYsMwGyQ7KFjGa/v7j
        Xk3q6NqYjN2MZQHQU33ICviThz9NDejgY42eoz1WT4RyBXsGGb4DGCVryIevZi5y
        zgAm73CUWI4rDYYlNCxF4t0PHt+TRI0V8bfqFxObOsQRdSC16zrDbibEkgzD5P+B
        PWhDiBB/XTwwu525uskGBFHKw8DF0KGK7Xk1uCnbn4V/UmFCC6R/a99UuhgP+M6/
        n/AqaqJxs873jV0iTSD9RXglVrfZT1lnWd0huflqoocBw+/VxMBSas5Iw0b05634
        /NpaFP1277hNBLx3DFO41+42BsXUzIM3p/E6ak2MmshfCHagUO2pm+lskDEkO4ze
        5w==
        -----END CERTIFICATE-----
    organization-name: "triplec"
    application-name: "AIGC"