name: Server CI/CD

on:
  push:
    paths:
      - 'server/**'
  pull_request:
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Print debug info
        run: |
          echo "GitHub Action job ID: ${{ github.run_id }}"
          echo "GitHub Action pipeline ID: ${{ github.run_number }}"
          echo "server build"
          
      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.HUB_USERNAME }} -p ${{ secrets.HUB_PASSWORD }} ${{ secrets.HUB_HOST }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: server/
          build-args: |
            VERSION=0.0.${{ github.run_number }}
          push: true
          tags: |
            ${{ secrets.HUB_HOST }}/aigc-video/aigc-video-server:0.0.${{ github.run_number }}
            ${{ secrets.HUB_HOST }}/aigc-video/aigc-video-server:latest
            
  test:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Run tests
        run: echo "server test" 